name: Deploy to GitHub Pages

on:
  # 当推送到 main 分支时触发部署 (如果你的默认分支是 master，请改为 master)
  push:
    branches: ['main']

# 设置 GITHUB_TOKEN 的权限，以允许部署到 GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# 只允许同时进行一次部署，跳过正在运行和最新提交之间的部署队列
concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 25 # 可以根据你的实际 Node 版本调整

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          run_install: false
          version: 10
          
      - name: Install dependencies
        run: pnpm install # 如果你用 pnpm 或 yarn，请修改这里
        
      - name: Build
        run: pnpm build
        
      - name: Setup Pages
        uses: actions/configure-pages@v4
        
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Vite 默认的打包输出目录是 dist
          path: './dist'
          
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4